### ISSUE TITLE
If no ID present in Sprite Listing, ignore it

### ISSUE THREAD

**Issue by miketrethewey** [alttpj/MemeforceHunt#34]
In preparation for including the rest of the sprites that aren't there yet, let's get the metadata ready. If the metadata is there, but the sprite file isn't there yet, ignore it. The `id` tag should be sufficient with figuring out whether or not the thing is there or not.

**Comment by bmhm** [comment]
Thanks, I haven't thought of such a use case. This should go into 2.1.0.

**Comment by bmhm** [comment]
Hi @miketrethewey  I thought a little more about this.
We are talking about the sprites which are being shipped with the application. I do not see a useful use case where you would want to have the metadata ready and merged into the trunk.
Creating IDs is just creating a new [ULID](https://github.com/ulid/spec).

You can use various tools to create one. You can even start a pull request and update it from time to time. I will happily merge it as soon as there are ULIDs present for each sprite.

If you see a reason to merge sprites before they have a valid ID, just post it here. Please just do not commit to trunk yet, a branch which we could merge some other time might be very useful for this.
